version: "3.8"
services:
  api:
    image: lrnzo349/staging-labres:latest
    ports:
      - "5001:5001"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
