services:
  api:
    container_name: 
    image: ghcr.io/ctrlaltelite-devs/labres-manager-server:staging
    ports:
      - "5031:5031"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - APP_ENV=staging