name: Deploy to VPS via Docker

on: 
    push:
        branches:
            - staging

env: 
    IMAGE_NAME: lrnzo349/staging-labres

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            
            - name: Set up Docker Buildx                
              uses: docker/setup-buildx-action@v3
            
            - name: Log in to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build and push Docker images
              run: |
                docker build -t $IMAGE_NAME:latest -t $IMAGE_NAME:${{ github.sha }}
                docker push $IMAGE_NAME:latest
                docker push $IMAGE_NAME:${{ github.sha }}

            - name: Deploy to Staging VPS
              uses: appleboy/ssh-action@v1.0.3
              with:
                host: ${{ secrets.VPS_HOST }}
                username: ${VPS_HOST%@}
                key: ${{ secrets.VPS_SSH_KEY }}
                script: |
                    cd ~/projects/labres-server/staging || mkdir -p ~/projects/labres-server/staging && cd ~/projects/labres-server/staging
                    if [ ! -d labres-manager-server ]; then
                        git clone --branch staging git@github.com:CtrlAltElite-Devs/labres-manager-server.git
                    else
                        cd labres-manager-server
                        git fetch origin
                        git checkout staging
                        git pull origin staging
                    fi

                    docker pull lrnzo349/staging-labres:latest
                    docker stack deploy -c docker-compose.yml labres_staging





